### ISSUE TITLE
    temperature = round(json_data["main"]["temp"]-273,1) KeyError: 'main'

### ISSUE THREAD

**Issue by puraabk20** [PrettyPrinted/weather_app_django#11]
import requests

api_address = "http://api.openweathermap.org/data/2.5/weather?id=524901&appid=" + key
json_data = requests.get(api_address).json()

def temp():
    temperature = round(json_data["main"]["temp"]-273,1)
    return temperature

def des():
    description = json_data["weather"][0]["description"]
    return description

print(temp())
print(des())

This was the Code I was Using and I got this error

Traceback (most recent call last):
  File "C:/Users/Puraab6656522/PycharmProjects/Puraab16352/Nova_Weather.py", line 15, in <module>
    print(temp())
  File "C:/Users/Puraab6656522/PycharmProjects/Puraab16352/Nova_Weather.py", line 8, in temp
    temperature = round(json_data["main"]["temp"]-273,1)
KeyError: 'main'

**Comment by jesse-mugweru** [comment]
How did you go by it ?

**Comment by yash617** [comment]
How did you fix it ?

**Comment by Zeesky-code** [comment]
I have been having this problem too. Have you been able to fix it?

**Comment by puraabk20** [comment]
no not at all
